### ISSUE TITLE
github actions is migrating to Node.js 20, requiring a new version of the action.

### ISSUE THREAD

**Issue by steve-mavens** [dhall-lang/setup-dhall#10]
Not specific to this action, but all over github everyone is getting warnings like the following:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, dhall-lang/setup-dhall@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Will there be a release of this action to use v20? The last time this migration happened was 12 -> 16, and the commit for that looks trivial: https://github.com/dhall-lang/setup-dhall/pull/6 I'm not a JS developer and I don't know whether there are any breaking changes that would need to be dealt with.

**Comment by craig-day** [comment]
This will be resolved by #11

**Comment by craig-day** [comment]
`v4` was updated with node20

**Comment by steve-mavens** [comment]
Thank you!
